# Generated by Django 3.2.7 on 2021-10-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SigningUp',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('email', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=213, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
