# Generated by Django 3.2.7 on 2021-10-27 06:50

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.product_images),
        ),
    ]
